version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: metal-backend
    ports:
      - "${APPLICATION_PORT:-4000}:4000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - APPLICATION_PORT=4000
      - APPLICATION_URL=${APPLICATION_URL}
      - ALLOWED_ORIGIN=${ALLOWED_ORIGIN}
      - COOKIES_SECRET=${COOKIES_SECRET}
      - SESSION_SECRET=${SESSION_SECRET}
      - SESSION_NAME=${SESSION_NAME}
      - SESSION_DOMAIN=${SESSION_DOMAIN}
      - SESSION_MAX_AGE=${SESSION_MAX_AGE}
      - SESSION_HTTP_ONLY=${SESSION_HTTP_ONLY}
      - SESSION_SECURE=${SESSION_SECURE}
      - SESSION_FOLDER=${SESSION_FOLDER}
      - POSTGRES_URI=${POSTGRES_URI}
      - REDIS_URI=${REDIS_URI}
      - GOOGLE_RECAPTCHA_SECRET_KEY=${GOOGLE_RECAPTCHA_SECRET_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_LOGIN=${MAIL_LOGIN}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_FROM=${MAIL_FROM}
    restart: unless-stopped
    networks:
      - backend

networks:
  backend:
    driver: bridge
